projConfig.toml for xlU_go

[meta]
    version = '0.1.0'

[project]
    name = 'xlU_go'  # distro name
    package = 'xlU_go'  # internal name
    main_lang = 'go'
    version = '0.7.12'
    version_date = '2017-05-23'
    author = 'Jim Dixon'
    author_email = 'jddixon@gmail.com'
    copyright = '2014-2017'
    description = 'library and utilities for managing content-keyed stores'
    dev_status = 'beta'
    license = 'mit'
    relpath = 'go/src/github.com/jddixon/xlU_go'
    state = 'shared'
    url = 'https://jddixon.github.io/xlU_go'

[go]
    cmds=[]
